trigger:
- main

pool:
  name: 'Default'
  demands:
    - agent.name -equals LOKMANE

steps:
# Étape 1 : Récupérer le code
- checkout: self

# Étape 2 : Construire et pusher l'image Docker
- task: Docker@2
  inputs:
    command: buildAndPush
    repository: mycontainerregistry.azurecr.io/my-python-app
    Dockerfile: '**/Dockerfile'
    containerRegistry: 'AzureDockerConnection'
    tags: |
      latest
      $(Build.BuildId)

# Étape 3 : Se connecter à l'ACR
- script: |
    az acr login --name mycontainerregistry
  displayName: 'Log in to ACR'

# Étape 4 : Exécuter le conteneur Docker avec mémoire augmentée
- script: |
    docker run -m 1g -p 4000:80 mycontainerregistry.azurecr.io/my-python-app:latest
  displayName: 'Run Docker container'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
