trigger:
- main

pool:
  name: 'Default'  # Ensure this matches your agent pool name
  demands:
    - agent.name -equals LOKMANE  # Replace with your actual agent name

steps:
# Step 1: Checkout the code
- checkout: self

# Step 2: Log in to Azure and ACR
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureDockerConnection'  # Replace with your Azure DevOps service connection name
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name mycontainerregistry

# Step 3: Build and push the Docker image
- task: Docker@2
  inputs:
    command: buildAndPush
    repository: azurecontainerregistryconnection.azurecr.io/my-python-app
    Dockerfile: '**/Dockerfile'
    containerRegistry: 'AzureDockerConnection'
    tags: |
      latest
      $(Build.BuildId)

# Step 4: Run the Docker container with increased memory
- script: |
    docker run -m 1g -p 4000:80 azurecontainerregistryconnection.azurecr.io/my-python-app:latest
  displayName: 'Run Docker container'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
