trigger:
- main

pool:
  name: 'Default'
  demands:
    - agent.name -equals LOKMANE

variables:
  azureSubscription: 'AzureDockerConnection'  # Replace with your Azure subscription name

steps:
# Step 1: Checkout the code
- checkout: self

# Step 2: Log in to Azure Container Registry (ACR)
- task: Docker@2
  inputs:
    command: login
    containerRegistry: 'AzureDockerConnection'  # The name of your dockerregistry service connection

# Step 3: Build and push the Docker image
- task: Docker@2
  inputs:
    command: buildAndPush
    repository: azurecontainerregistryconnection.azurecr.io/my-python-app  # Ensure repository name is lowercase
    Dockerfile: '**/Dockerfile'
    containerRegistry: 'AzureDockerConnection'
    tags: |
      latest
      $(Build.BuildId)

# Step 4: Deploy to Azure App Service
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'Azureserviceconnection'  # Replace with your Azure service connection name for App Service
    appName: 'WebAppOnAzure'  # Replace with the name of your Azure App Service
    imageName: 'azurecontainerregistryconnection.azurecr.io/my-python-app'
    tag: 'latest'
