trigger:
- main

pool:
  name: 'Default'  # Make sure this matches your agent pool name
  demands:
    - agent.name -equals LOKMANE  # Replace with your actual agent name

steps:
- checkout: self
- script: |
    python hello_world.py
  displayName: 'Run Hello World script'
